ALTER TABLE inventory_items ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE orders ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE shipments ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
