FROM maven:3.9.9-eclipse-temurin-21 AS build
WORKDIR /workspace
ARG MODULE
COPY pom.xml .
COPY common ./common
COPY api-gateway ./api-gateway
COPY user-service ./user-service
COPY order-service ./order-service
COPY inventory-service ./inventory-service
COPY warehouse-service ./warehouse-service
COPY shipment-service ./shipment-service
RUN mvn -pl ${MODULE} -am -DskipTests package

FROM eclipse-temurin:21-jre
WORKDIR /app
ARG MODULE
COPY --from=build /workspace/${MODULE}/target/*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java","-jar","/app/app.jar"]
