apiVersion: v1
kind: ConfigMap
metadata:
  name: kml-config
  namespace: kml
data:
  SPRING_PROFILES_ACTIVE: "k8s"
  KML_POSTGRES_HOST: "postgres.kml.svc.cluster.local"
  KML_POSTGRES_PORT: "5432"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka.kml.svc.cluster.local:9092"
  SPRING_RABBITMQ_HOST: "rabbitmq.kml.svc.cluster.local"
  KML_OPENSEARCH_URL: "http://opensearch.kml.svc.cluster.local:9200"
  MANAGEMENT_ENDPOINTS_WEB_BASE_PATH: "/actuator"
  MANAGEMENT_ENDPOINT_PROMETHEUS_ACCESS: "unrestricted"
  MANAGEMENT_TRACING_ENABLED: "true"
  MANAGEMENT_TRACING_SAMPLING_PROBABILITY: "1.0"
  MANAGEMENT_OTLP_TRACING_ENDPOINT: "http://otel-collector.kml.svc.cluster.local:4318/v1/traces"
